create database hr_analytics;
use hr_analytics;

create table employee (
Age int,
Attrition varchar(10),
BusinessTravel varchar(50),
DailyRate int,
Department varchar(50),
DistanceFromHome int,
EmployeeNumber int,
Education int,
EducationField varchar(50),
EnviornmentSatisfaction int,
Gender Varchar(10),
HourlyRate int,
JobInvolvement int,
Joblevel int,
JobRole varchar(50),
JobSatisfaction int,
MartialStatus varchar(20),
MonthlyIncome int,
MonthlyRate int,
NumCompaniesWorked  int,
OverTime Varchar(10),
PercentageSalaryHike int,
PerformaneRating int,
RelationshipSatisfaction int,
StockOptionLevel int,
TotalWorkingYear int,
TrainingTimesLastYear int,
WorkLifeBalnce int,
YearsAtCompany int,
YearsInCurrentRole int,
YearsSinceLastPromotion int,
YearsWithCurrManager int);